CREATE NONCLUSTERED INDEX IX_Table_DDL_Exixsting ON ver.Table_DDL_Exixsting
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
